# Generated by Django 6.1 on 2026-10-09 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0013_alter_calculooperacion_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInicialCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo inicial')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_iniciales', to='caja.caja')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='divisas.divisa')),
            ],
            options={
                'verbose_name': 'Saldo inicial de caja',
                'verbose_name_plural': 'Saldos iniciales de caja',
                'ordering': ['divisa__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='una_sola_caja_abierta_por_cajero'),
        ),
        migrations.AddConstraint(
            model_name='saldoinicialcaja',
            constraint=models.UniqueConstraint(fields=('caja', 'divisa'), name='saldo_inicial_unico_por_caja_y_divisa'),
        ),
    ]
