"""Vincula el perfil de cliente con su usuario titular."""
# Generated by Django 6.1 on 2026-08-31 13:05

import django.db.models.deletion
from django.conf import settings
"""Vincula el perfil de cliente con su usuario titular."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Agrega la relación de titularidad entre cliente y usuario."""

    dependencies = [
        ('clientes', '0003_cliente_fecha_registro_cliente_identificador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
    ]
