# Generated by Django 6.1 on 2026-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Baja lógica: False indica que el cliente está inactivo sin eliminar sus datos físicamente.', verbose_name='Activo'),
        ),
    ]
