# Generated by Django 6.1 on 2026-09-06 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que tienen acceso a gestionar o representar a este cliente.', related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del Sistema Asociados'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Baja lógica del cliente.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('PREMIUM', 'Premium'), ('VIP', 'VIP'), ('CORPORATIVO', 'Corporativo')], default='ESTANDAR', help_text='Permite clasificar al cliente.', max_length=20, verbose_name='Segmento / Categoría'),
        ),
    ]
