# Generated by Django 6.1 on 2026-09-07 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='clientes_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Autorizados'),
        ),
    ]
