# Generated by Django 6.1 on 2026-09-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_user_cliente_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuarios',
            new_name='user',
        ),
    ]
