# Generated by Django 6.1 on 2026-09-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_rename_usuarios_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuarios',
        ),
    ]
