"""Restaura el usuario titular opcional del perfil de cliente."""
# Generated by Django 6.1 on 2026-09-06 21:56

import django.db.models.deletion
from django.conf import settings
"""Restaura el usuario titular opcional del perfil de cliente."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Agrega la relación titular compatible con datos existentes."""

    dependencies = [
        ('clientes', '0009_rename_user_cliente_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario propietario o principal vinculado a este perfil de cliente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Titular'),
        ),
    ]
