# Generated by Django 6.1 on 2026-09-11 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Débito/Crédito'), ('BILLETERA', 'Billetera Digital')], max_length=20, verbose_name='Tipo de Medio de Pago')),
                ('nombre_titular', models.CharField(max_length=150, verbose_name='Nombre del Titular')),
                ('entidad_financiera', models.CharField(max_length=100, verbose_name='Entidad Financiera / Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta / Alias')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORRO', 'Caja de Ahorro'), ('CORRIENTE', 'Cuenta Corriente')], max_length=20, null=True, verbose_name='Tipo de Cuenta')),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos')),
                ('es_predeterminado', models.BooleanField(default=False, verbose_name='¿Es Predeterminado?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['-es_predeterminado', '-creado_en'],
            },
        ),
    ]
