# Generated by Django 6.1 on 2026-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_comision_personalizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='ultimos_4_digitos',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Número de Tarjeta'),
        ),
    ]
