"""Agrega el estado 'Cancelada por cambio de cotización' a las transacciones.

Solo cambia las opciones válidas hacia adelante (metadata, no migra datos):
la HU "Cancelación de operación por cambio de cotización" (GE-76) hace que
la pantalla de confirmación cancele automáticamente una transacción
"Pendiente de confirmación" con este nuevo estado, en vez de solo bloquear
la confirmación, cuando la tasa vigente ya no coincide con la usada al
calcular. Queda distinguible de la cancelación manual ('Cancelada') tanto en
la pantalla de confirmación como en el historial de transacciones.
"""

# Generated by Django 6.1 on 2026-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0011_configuracionvigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculooperacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='calculotriangulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
    ]
