# Generated by Django 6.1 on 2026-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0011_configuracionvigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculooperacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='calculotriangulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
    ]
