# Generated by Django 6.1 on 2026-10-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_remove_metodopago_ultimos_4_digitos_and_more'),
        ('divisas', '0012_alter_calculooperacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculooperacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización'), ('PAGADA', 'Pagada')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='calculotriangulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización'), ('PAGADA', 'Pagada')], default='PENDIENTE_CONFIRMACION', max_length=25),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Débito/Crédito'), ('BILLETERA', 'Billetera Digital')], max_length=20)),
                ('proveedor', models.CharField(help_text='Quién confirmó el pago: MANUAL (esta HU), o un proveedor real como STRIPE/SIPAP.', max_length=30)),
                ('identificador_externo', models.CharField(help_text='Identificador del pago para ese proveedor (p. ej. el id de un PaymentIntent de Stripe).', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('calculo_operacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='divisas.calculooperacion', verbose_name='Compra o venta pagada')),
                ('calculo_triangulacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='divisas.calculotriangulacion', verbose_name='Cambio de divisas pagado')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='clientes.metodopago', verbose_name='Método de pago guardado utilizado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'identificador_externo'), name='pago_unico_por_proveedor_e_identificador')],
            },
        ),
    ]
