# Generated by Django 6.1 on 2026-08-30 22:32

"""Crea los modelos iniciales de autenticación."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica la estructura inicial de la aplicación de autenticación."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoProtegido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
